- name: Setup EC2 instance with Docker and Nginx
  hosts: ec2
  become: yes
  tasks:
    - name: Update packages (Amazon Linux)
      command: amazon-linux-extras enable nginx1
      when: ansible_distribution == "Amazon"

    - name: Install required packages
      package:
        name: "{{ item }}"
        state: present
      loop:
        - docker
        - nginx

    - name: Enable and start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Enable and start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes
