name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change if using a different branch
  workflow_dispatch:  # Allows manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to AWS ECR
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin YOUR_ECR_URI

      - name: Build and push Docker image
        run: |
          docker build -t devops-app .
          docker tag devops-app:latest YOUR_ECR_URI/devops-app:latest
          docker push YOUR_ECR_URI/devops-app:latest

      - name: SSH into EC2 and deploy container
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ec2-user@YOUR_EC2_PUBLIC_IP << 'EOF'
          docker stop devops-app || true
          docker rm devops-app || true
          docker pull YOUR_ECR_URI/devops-app:latest
          docker run -d -p 8080:80 --name devops-app YOUR_ECR_URI/devops-app:latest
          EOF
